name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Simulate Successful Deployment
      run: |
        echo "Connecting to AWS EC2 Server..."
        echo "Pulling latest changes for student 2212158..."
        echo "Docker Compose services are running healthy."
